name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact (v4-safe)
        uses: actions/upload-artifact@v4  # ⚠️ نسخه جدید و رسمی
        with:
          name: github-pages
          path: './'  # مسیر پوشه نهایی برای دیپلوی (مثلاً ./dist برای پروژه‌های buildشده)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
