# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]  # اجرا فقط هنگام push روی شاخه main
  workflow_dispatch:     # امکان اجرای دستی از Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Build your project (optional)
        run: |
          echo "✅ No build step specified. Add your build command here if needed."

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'  # مسیر فایل‌های نهایی برای انتشار (می‌تونی به ./dist یا ./build تغییر بدی)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
