name: "MTProto Collector"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Run PHP Script
        run: php main.php

      - name: Configure Git
        run: |
          git config --global user.name "3yed82"
          git config --global user.email "git82@3yed.eu.org"

      - name: Commit and Push if Changes Exist
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "🚀 Proxies Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi
